# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 35471c006f89279412d7bd1891ef0914c69388076915b922c22ff6e74746c7236a083d9dd0266415b2257c1b2e7d0ea3b3e3d24204efacd30f186a5424f478fc

test:
  secret_key_base: 525e792edb344a5bdb7f3f168fd98711dbf6eb71698473aa39f12dcab3690d415f6278ab2e7487df84771632c5b23ed2b5fbea4343b859d6e0b3ba3ca6e0c9de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
